name: Deploy to Hero-MyWebClass

on:
  push:
    branches:
      - main
      - development
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 143.244.223.251 >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa kl63@143.244.223.251 "echo 'SSH connection successful'" || exit 1

      - name: Configure passwordless sudo
        run: |
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa kl63@143.244.223.251 \
          "echo 'kl63 ALL=(ALL) NOPASSWD: /usr/bin/rsync' | sudo -S tee /etc/sudoers.d/kl63-rsync"

      - name: Set deployment directory
        id: set-deploy-dir
        run: |
          case "${{ github.ref_name }}" in
            main)
              echo "DEPLOY_DIR=/var/www/html/production" >> $GITHUB_ENV ;;
            development)
              echo "DEPLOY_DIR=/var/www/html/development" >> $GITHUB_ENV ;;
            QA)
              echo "DEPLOY_DIR=/var/www/html/QA" >> $GITHUB_ENV ;;
            *)
              echo "Unknown branch: ${{ github.ref_name }}" >&2
              exit 1 ;;
          esac

      - name: Verify build directory
        run: |
          if [ ! -d "./build" ]; then
            echo "Build directory not found. Please check your build process."
            exit 1
          fi

      - name: Deploy to server
        run: |
          rsync -avz --progress --delete ./build/ kl63@143.244.223.251:${{ env.DEPLOY_DIR }}/ --rsync-path="sudo rsync"

      - name: Clean up sudoers
        run: |
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa kl63@143.244.223.251 \
          "sudo rm /etc/sudoers.d/kl63-rsync"
