name: Deploy to Hero-MyWebClass

on:
  push:
    branches:
      - main
      - development
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure SSH key
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Add remote host to known_hosts
      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      # Test SSH connection with verbose logging
      - name: Test SSH connection
        run: |
          ssh -v -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@$REMOTE_HOST "echo 'SSH connection successful'"

      # Deploy the built files using rsync
      - name: Deploy to server
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: |
          rsync -avz --delete ./build/ ${{ secrets.REMOTE_USER }}@$REMOTE_HOST:/var/www/html/
