name: Deploy to Hero-MyWebClass

on:
  push:
    branches:
      - main
      - development
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure SSH key
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 143.244.223.251 >> ~/.ssh/known_hosts

      # Test SSH connection
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa kl63@143.244.223.251 "echo 'SSH connection successful'"

      # Set deployment directory based on branch
      - name: Set deployment directory
        id: set-deploy-dir
        run: |
          case "${{ github.ref_name }}" in
            main)
              echo "DEPLOY_DIR=/var/www/html/production" >> $GITHUB_ENV ;;
            development)
              echo "DEPLOY_DIR=/var/www/html/development" >> $GITHUB_ENV ;;
            QA)
              echo "DEPLOY_DIR=/var/www/html/QA" >> $GITHUB_ENV ;;
            *)
              echo "Unknown branch: ${{ github.ref_name }}"
              exit 1 ;;
          esac

      # Deploy files using rsync
      - name: Deploy to server
        run: |
          rsync -avz --delete ./build/ kl63@143.244.223.251:/var/www/html/development/ --rsync-path="sudo rsync"

