name: Deploy to Hero-MyWebClass

on:
  push:
    branches:
      - main
      - development
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure SSH key
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Determine deployment directory based on branch
      - name: Set deployment directory
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "DEPLOY_DIR=/var/www/html/production" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "development" ]; then
            echo "DEPLOY_DIR=/var/www/html/development" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "QA" ]; then
            echo "DEPLOY_DIR=/var/www/html/QA" >> $GITHUB_ENV
          fi

      # Add remote host to known_hosts
      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -H 143.244.223.251 >> ~/.ssh/known_hosts

      # Test SSH connection with verbose logging
      - name: Test SSH connection
        run: |
          ssh -v -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@143.244.223.251 "echo 'SSH connection successful'"

      # Deploy the built files using rsync
      - name: Deploy to server
        env:
          REMOTE_HOST: 143.244.223.251
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          DEPLOY_DIR: ${{ env.DEPLOY_DIR }}
        run: |
          rsync -avz --delete ./build/ $REMOTE_USER@$REMOTE_HOST:$DEPLOY_DIR/
